config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :projects
  resources :galaxies

  root "home#index"
  get "/dash", to: "dash#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
end

app/models/galaxy.rb
class Galaxy < ApplicationRecord
    belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
    has_many :galaxies
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :projects
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/dash_controller.rb
class DashController < ApplicationController
    before_action :authenticate_user!

    def index
    end
end

app/controllers/galaxies_controller.rb
class GalaxiesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @galaxies = Galaxy.all
  end

  def show
    @galaxy = Galaxy.find(params[:id])
  end

  def new
    @galaxy = Galaxy.new
    @project_id = params[:project_id]
    @url = params[:url]
  end

  def create
    project = Project.find(galaxy_params[:project_id])
    if current_user.id != project.user_id
      flash[:alert] = "cant create a galaxy in someone elses project"
      redirect_to galaxies_path
    end
    url = params[:url]
    galaxy = project.galaxies.create(galaxy_params)
    if url != ""
      redirect_to url
    else
      redirect_to galaxies_path
    end
  end

  def update
    @galaxy = Galaxy.find(params[:id])
    project = Project.find(galaxy_params[:project_id])
    if current_user.id != project.user_id
      flash[:alert] = "cant edit someone elses galaxy"
    end
    @galaxy.update(galaxy_params)
    url = params[:url]
    if url != ""
      redirect_to url
    else
      redirect_to galaxies_path
    end
  end

  def edit
    @galaxy = Galaxy.find(params[:id])
    @project_id = params[:project_id]
    @url = params[:url]
  end

  def destroy
    @project = Project.find(params[:project_id])
    @galaxy = Galaxy.find(params[:id])
    if current_user.id != @project.user_id || @galaxy.project_id != @project.id
      flas[:alert] = "cant edit somone elses project"
    end
    @galaxy.destroy

    url = params[:url]
    if url ""
      redirect_to url
    else
      redirect_to galaxies_path
    end
  end

  private

  def galaxy_params
    params.require(:galaxy).permit(:name, :description, :project_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    project = current_user.projects.create(project_params)

    redirect_to projects_path
  end
    

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if current_user.id != @project.user_id
      flash[:alert] = "cant edit somone elses project"
      redirect_to projects_path and return 
    end
    @project.update(project_params)
    redirect_to project_path(@project)
  end

  def destroy
    @project = Project.find(params[:id])
    if current_user.id != @project.user_id
      flash[:alert] = "cant remove somone elses project"
      redirect_to projects_path and return 
    end
    @project.destroy

    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit( :name, :description)
  end
end

app/helpers/active_sessions_helper.rb
module ActiveSessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/dash_helper.rb
module DashHelper
end

app/helpers/galaxies_helper.rb
module GalaxiesHelper
end

app/helpers/home/index_helper.rb
module Home::IndexHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dash/index.html.haml
.list-block
    %h1 Projects
    %table
        - current_user.projects.each do |project|
            %tr.dark-item
                %td{"data-controller" => "proj", "data-desc" => project.description} 
                    = link_to project.name, "/projects/#{project.id}"
                %td 
                    = button_to 'Edit', edit_project_path(project), method: 'get'
                %td 
                    = button_to 'Remove', project, method: :delete, data: { confirm: 'Are you sure?' }
    = button_to 'Create', new_project_path, method: "get"
.list-block-no-create
    %h1 Galaxies
    %table
        - current_user.projects.each do |project|
            - project.galaxies.each do |galaxy|
                %tr.dark-item
                    %td
                        = link_to galaxy.name, "/galaxies/#{galaxy.id}"
                        %div{"data-controller" => "proj", "data-desc" => galaxy.description} 
                        project:
                        = link_to project.name, "/projects/#{project.id}"


                    %td 
                        = button_to 'Edit', edit_galaxy_path(galaxy), method: 'get'
                    %td 
                        = button_to 'Remove', galaxy, method: :delete, data: { confirm: 'Are you sure?' }

app/views/galaxies/edit.html.haml
%h3 Update Galaxy Details
= form_with class: "proj-form", model: @galaxy do |form|
    = form.text_field :name, placeholder: "name"
    = form.text_area :description, placeholder: "description", rows: 20
    = form.hidden_field :project_id, value: @project_id
    = hidden_field_tag :url, @url
    = form.submit

app/views/galaxies/index.html.haml
%table
    - @galaxies.each do |galaxy|
        %tr.proj
            %td{"data-controller" => "proj", "data-desc" => galaxy.description} 
                = link_to galaxy.name, "/galaxies/#{galaxy.id}"
                %p 
                    author:
                    = User.find(Project.find(galaxy.project_id).user_id).username

app/views/galaxies/new.html.haml
%h3 Create a Galaxy
= form_with class: "proj-form", model: @galaxy do |form|
    = form.text_field :name, placeholder: "name"
    = form.text_area :description, placeholder: "description", rows: 20
    = form.hidden_field :project_id, value: @project_id
    = hidden_field_tag :url, @url
    = form.submit

app/views/galaxies/show.html.haml
#galaxy
  %h1.title
    = @galaxy.name
  %div{"data-controller" => "proj", "data-desc" => @galaxy.description}
  
  = button_to 'Remove', @galaxy, method: :delete, data: { confirm: 'Are you sure?' }
  = button_to 'Edit', edit_galaxy_path(@galaxy), params: { :url => "/galaxies/#{@galaxy.id}", :project_id => @galaxy.project_id }, method: 'get'

app/views/home/index.html.haml
#home
    - if user_signed_in?
        %h1.welcome
            Welcome
            = current_user.username
        = button_to "Edit My Acount", edit_user_registration_path, method: :get 
        = button_to "Sign Out", destroy_user_session_path, method: :delete
 
    - else
        .buttons
            = button_to "Sign In", new_user_session_path, method: :get 
            = button_to "Sign Up", new_user_registration_path, method: :get 
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorldTool</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunitol">
  </head>
  <body>
    <%= render "shared/header" %>
   <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/projects/edit.html.haml
%h3 Update Project Details
= form_with class: "proj-form", model: @project do |form|
  = form.text_field :name, placeholder: "name"
  = form.text_area :description, placeholder: "description", rows: 20
  = form.submit

app/views/projects/index.html.haml
%table
    - @projects.each do |project|
        %tr.proj
            %td{"data-controller" => "proj", "data-desc" => project.description} 
                = link_to project.name, "/projects/#{project.id}"
                %p 
                    author:
                    = User.find(project.user_id).username

app/views/projects/new.html.haml
%h3 Create a Project
= form_with class: "proj-form", model: @project do |form|
  = form.text_field :name, placeholder: "name"
  = form.text_area :description, placeholder: "description", rows: 20
  = form.submit

app/views/projects/show.html.haml
#proj
  %h1.title
    = @project.name
  %div{"data-controller" => "proj", "data-desc" => @project.description}
  .list-block
    %h1 Galaxies
    %table
      - @project.galaxies.each do |galaxy|
        %tr.dark-item
          %td{"data-controller" => "proj", "data-desc" => galaxy.description} 
            = link_to galaxy.name, "/galaxies/#{galaxy.id}"
          %td 
            = button_to 'Edit', edit_galaxy_path(galaxy), params: {:project_id => @project.id, :id => galaxy.id, :url => "/projects/#{@project.id}" }, method: 'get'
          %td 
            = button_to 'Remove', galaxy, params: { :project_id => @project.id, :url => "/projects/#{@project.id}" }, method: :delete, data: { confirm: 'Are you sure?' }

    = button_to 'Create', new_galaxy_path, params: {:project_id => @project.id, :url => "/projects/#{@project.id}"}, method: "get"
  
  = button_to 'Remove', @project, method: :delete, data: { confirm: 'Are you sure?' }
  = button_to 'Edit', edit_project_path(@project), method: 'get'

app/views/shared/_header.html.haml
%header
    %nav#nav
        %a{:href => "/"} home
        %a{:href => "/dash"} dashboard
        %a{:href => "/projects"} browse
    #nav-dropdown{"data-controller" => "dropdown"}
        .container 
            %button#dropbtn{"data-action" => "click->dropdown#showHide"} &#9776;
        %nav#nav-contents.hide{"data-dropdown-target" => "hideable"}
            %a{:href => "/"} home
            %a{:href => "/dash"} dashboard
            %a{:href => "/browse"} browse